version: '3.9'
services:
  # Nếu bạn có nhiều tệp docker-compose.yml khác nhau, 
  # trong đó các dịch vụ (services) có cùng tên,NO PROBLEM !, 
  # Docker Compose sẽ tự động tạo ra một namespace cho mỗi dự án
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: stock_app_db
    environment:
      #Environment variables
      - ACCEPT_EULA=Y #Accept End-User License Agreement
      - SA_PASSWORD=Abc123456789@
    ports: #Port mapping from container to host
      - "1434:1433"
    volumes: #Mapping data directory from container to host(laptop, PC)       
      - ./db_data:/var/opt/mssql/data
      #- ./sql_init:/docker-entrypoint-initdb.d #sql_init contains SQL scripts
    restart: always
    mem_limit: 12g # Memory limit for the container
    memswap_limit: 13g

#docker-compose --file ./docker-compose.yml up --detach
#docker-compose ps
#docker exec -it stock_app_db /bin/bash
